### ISSUE TITLE
项目都无法运行

### ISSUE THREAD

**Issue by wangxp423** [MicalLannister/RecyclerViewDemo#1]
你的项目都不能运行，提交到github 干嘛来了？然后来在其他地方推广？

**Comment by MicalLannister** [comment]
从写clone下来运行了一遍，可以运行的，你clone下来运行如果有什么问题你就把问题发出来看吧~

**Comment by xiaozhao0331** [comment]
我也运行不了  没有报错  ....
编译都不编译

**Comment by xiaozhao0331** [comment]
代码拷到新项目里 可以运行了  多选 控制选中个数 没有看到这个设置呀

**Comment by MicalLannister** [comment]
> 代码拷到新项目里 可以运行了 多选 控制选中个数 没有看到这个设置呀

这个项目的AbsRecycleAdapter没有实现控制多选个数的逻辑，这个你可以修改下实现，后面我也会考虑把这个需求放进去。
